name: Clang Format Check

on: [push, pull_request]
jobs:
  macos64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install clang-format
        run: |
          brew install clang-format

      - name: Check the Formatting
        run: |
          ./formatcode.sh
          ./CI/check-format.sh
